# Generated by Django 3.1.5 on 2021-01-28 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210128_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='description',
            field=models.TextField(default='this is a text description new product'),
            preserve_default=False,
        ),
    ]
