# Generated by Django 3.1.5 on 2021-01-28 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='img/profile_image/agent', verbose_name='Profile Image'),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='img/profile_image/customer', verbose_name='Customer Image')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
